#!/bin/bash

MLFLOW_DATABASE_NAME="mlflow"
MLFLOW_USERNAME="mlflow"
MLFLOW_PASSWORD="clearml"
sudo mysql -e "
	CREATE DATABASE ${MLFLOW_DATABASE_NAME};
	CREATE USER '${MLFLOW_USERNAME}'@'localhost' IDENTIFIED BY '${MLFLOW_PASSWORD}';  
	GRANT ALL PRIVILEGES ON ${MLFLOW_DATABASE_NAME}.* TO '${MLFLOW_USERNAME}'@'localhost' WITH GRANT OPTION;
"

NGAS_DATABASE_NAME="ngas"
NGAS_USERNAME="ngas"
NGAS_PASSWORD="ngas"
sudo mysql -e "
  CREATE DATABASE ${NGAS_DATABASE_NAME};
	CREATE USER '${NGAS_USERNAME}'@'localhost' IDENTIFIED BY '${NGAS_PASSWORD}';
	GRANT ALL PRIVILEGES ON ${NGAS_DATABASE_NAME}.* TO '${NGAS_USERNAME}'@'localhost' WITH GRANT OPTION;
"

# Load ngas database tables from ngamsCreateTables-mySQL.sql